version: '3.6'
services:
  boiler:
    build:
      context: .
      target: dev
    volumes:
      - modules:/opt/app/node_modules
      - type: bind
        source: .
        target: /opt/app/
    ports:
      - 3000:3000

volumes:
  modules:
    driver: local
