version: '3.6'
services:
  boiler:
    build:
      context: .
      target: dev
    volumes:
      - modules:/opt/app/node_modules
      - type: bind
        source: .
        target: /opt/app/

volumes:
  modules:
    driver: local
