version: '3.6'
services:
  applicative:
    build: .
    volumes:
      - modules:/opt/boiler/node_modules
      - type: bind
        source: .
        target: /opt/boiler/

volumes:
  modules:
    driver: local
